name: AIO Params
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Echo provided inputs
        run: |
          echo "🌍 Cycle_Key: ${{ github.event.inputs. Cycle_Key }}"
          echo "✅ Project_key: ${{ github.event.inputs.Project_key }}"
          echo "📦 Case_key_list: ${{ github.event.inputs.Case_key_list }}"
          echo "📦 case_auto_key_list: ${{ github.event.inputs.case_auto_key_list }}"
          echo "📡 AIO_API_Token: ${{ github.event.inputs.AIO_API_Token }}"
      - run: echo "🍏 This job's status is ${{ job.status }}."
